// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/app.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoreReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  []byte   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	AccountToken         string   `protobuf:"bytes,3,opt,name=account_token,json=accountToken,proto3" json:"account_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreReq) Reset()         { *m = StoreReq{} }
func (m *StoreReq) String() string { return proto.CompactTextString(m) }
func (*StoreReq) ProtoMessage()    {}
func (*StoreReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{0}
}
func (m *StoreReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreReq.Unmarshal(m, b)
}
func (m *StoreReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreReq.Marshal(b, m, deterministic)
}
func (dst *StoreReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreReq.Merge(dst, src)
}
func (m *StoreReq) XXX_Size() int {
	return xxx_messageInfo_StoreReq.Size(m)
}
func (m *StoreReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreReq.DiscardUnknown(m)
}

var xxx_messageInfo_StoreReq proto.InternalMessageInfo

func (m *StoreReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreReq) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *StoreReq) GetAccountToken() string {
	if m != nil {
		return m.AccountToken
	}
	return ""
}

type StoreResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreResp) Reset()         { *m = StoreResp{} }
func (m *StoreResp) String() string { return proto.CompactTextString(m) }
func (*StoreResp) ProtoMessage()    {}
func (*StoreResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{1}
}
func (m *StoreResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreResp.Unmarshal(m, b)
}
func (m *StoreResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreResp.Marshal(b, m, deterministic)
}
func (dst *StoreResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreResp.Merge(dst, src)
}
func (m *StoreResp) XXX_Size() int {
	return xxx_messageInfo_StoreResp.Size(m)
}
func (m *StoreResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreResp.DiscardUnknown(m)
}

var xxx_messageInfo_StoreResp proto.InternalMessageInfo

type GetReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{2}
}
func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (dst *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(dst, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResp struct {
	Val                  []byte   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResp) Reset()         { *m = GetResp{} }
func (m *GetResp) String() string { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()    {}
func (*GetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{3}
}
func (m *GetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResp.Unmarshal(m, b)
}
func (m *GetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResp.Marshal(b, m, deterministic)
}
func (dst *GetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResp.Merge(dst, src)
}
func (m *GetResp) XXX_Size() int {
	return xxx_messageInfo_GetResp.Size(m)
}
func (m *GetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetResp proto.InternalMessageInfo

func (m *GetResp) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type DumpReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpReq) Reset()         { *m = DumpReq{} }
func (m *DumpReq) String() string { return proto.CompactTextString(m) }
func (*DumpReq) ProtoMessage()    {}
func (*DumpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{4}
}
func (m *DumpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpReq.Unmarshal(m, b)
}
func (m *DumpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpReq.Marshal(b, m, deterministic)
}
func (dst *DumpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpReq.Merge(dst, src)
}
func (m *DumpReq) XXX_Size() int {
	return xxx_messageInfo_DumpReq.Size(m)
}
func (m *DumpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpReq.DiscardUnknown(m)
}

var xxx_messageInfo_DumpReq proto.InternalMessageInfo

// Stream RPC
type DumpItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  []byte   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpItem) Reset()         { *m = DumpItem{} }
func (m *DumpItem) String() string { return proto.CompactTextString(m) }
func (*DumpItem) ProtoMessage()    {}
func (*DumpItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{5}
}
func (m *DumpItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpItem.Unmarshal(m, b)
}
func (m *DumpItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpItem.Marshal(b, m, deterministic)
}
func (dst *DumpItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpItem.Merge(dst, src)
}
func (m *DumpItem) XXX_Size() int {
	return xxx_messageInfo_DumpItem.Size(m)
}
func (m *DumpItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpItem.DiscardUnknown(m)
}

var xxx_messageInfo_DumpItem proto.InternalMessageInfo

func (m *DumpItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DumpItem) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type GetByTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByTokenReq) Reset()         { *m = GetByTokenReq{} }
func (m *GetByTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetByTokenReq) ProtoMessage()    {}
func (*GetByTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{6}
}
func (m *GetByTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByTokenReq.Unmarshal(m, b)
}
func (m *GetByTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByTokenReq.Marshal(b, m, deterministic)
}
func (dst *GetByTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByTokenReq.Merge(dst, src)
}
func (m *GetByTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetByTokenReq.Size(m)
}
func (m *GetByTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetByTokenReq proto.InternalMessageInfo

func (m *GetByTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetByTokenResp struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByTokenResp) Reset()         { *m = GetByTokenResp{} }
func (m *GetByTokenResp) String() string { return proto.CompactTextString(m) }
func (*GetByTokenResp) ProtoMessage()    {}
func (*GetByTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{7}
}
func (m *GetByTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByTokenResp.Unmarshal(m, b)
}
func (m *GetByTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByTokenResp.Marshal(b, m, deterministic)
}
func (dst *GetByTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByTokenResp.Merge(dst, src)
}
func (m *GetByTokenResp) XXX_Size() int {
	return xxx_messageInfo_GetByTokenResp.Size(m)
}
func (m *GetByTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetByTokenResp proto.InternalMessageInfo

func (m *GetByTokenResp) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type Account struct {
	MaxCacheKeys         int64    `protobuf:"varint,1,opt,name=max_cache_keys,json=maxCacheKeys,proto3" json:"max_cache_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{8}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetMaxCacheKeys() int64 {
	if m != nil {
		return m.MaxCacheKeys
	}
	return 0
}

type Error struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Temporary            bool     `protobuf:"varint,3,opt,name=temporary,proto3" json:"temporary,omitempty"`
	UserErrorCode        int64    `protobuf:"varint,4,opt,name=userErrorCode,proto3" json:"userErrorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_0233802bd5984bdb, []int{9}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetTemporary() bool {
	if m != nil {
		return m.Temporary
	}
	return false
}

func (m *Error) GetUserErrorCode() int64 {
	if m != nil {
		return m.UserErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*StoreReq)(nil), "rpc.StoreReq")
	proto.RegisterType((*StoreResp)(nil), "rpc.StoreResp")
	proto.RegisterType((*GetReq)(nil), "rpc.GetReq")
	proto.RegisterType((*GetResp)(nil), "rpc.GetResp")
	proto.RegisterType((*DumpReq)(nil), "rpc.DumpReq")
	proto.RegisterType((*DumpItem)(nil), "rpc.DumpItem")
	proto.RegisterType((*GetByTokenReq)(nil), "rpc.GetByTokenReq")
	proto.RegisterType((*GetByTokenResp)(nil), "rpc.GetByTokenResp")
	proto.RegisterType((*Account)(nil), "rpc.Account")
	proto.RegisterType((*Error)(nil), "rpc.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CacheClient is the client API for Cache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CacheClient interface {
	Store(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreResp, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error)
	Dump(ctx context.Context, in *DumpReq, opts ...grpc.CallOption) (Cache_DumpClient, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Store(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreResp, error) {
	out := new(StoreResp)
	err := c.cc.Invoke(ctx, "/rpc.Cache/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error) {
	out := new(GetResp)
	err := c.cc.Invoke(ctx, "/rpc.Cache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Dump(ctx context.Context, in *DumpReq, opts ...grpc.CallOption) (Cache_DumpClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cache_serviceDesc.Streams[0], "/rpc.Cache/Dump", opts...)
	if err != nil {
		return nil, err
	}
	x := &cacheDumpClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cache_DumpClient interface {
	Recv() (*DumpItem, error)
	grpc.ClientStream
}

type cacheDumpClient struct {
	grpc.ClientStream
}

func (x *cacheDumpClient) Recv() (*DumpItem, error) {
	m := new(DumpItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CacheServer is the server API for Cache service.
type CacheServer interface {
	Store(context.Context, *StoreReq) (*StoreResp, error)
	Get(context.Context, *GetReq) (*GetResp, error)
	Dump(*DumpReq, Cache_DumpServer) error
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Cache/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Store(ctx, req.(*StoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Dump_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DumpReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CacheServer).Dump(m, &cacheDumpServer{stream})
}

type Cache_DumpServer interface {
	Send(*DumpItem) error
	grpc.ServerStream
}

type cacheDumpServer struct {
	grpc.ServerStream
}

func (x *cacheDumpServer) Send(m *DumpItem) error {
	return x.ServerStream.SendMsg(m)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Cache_Store_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dump",
			Handler:       _Cache_Dump_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/app.proto",
}

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	GetByToken(ctx context.Context, in *GetByTokenReq, opts ...grpc.CallOption) (*GetByTokenResp, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) GetByToken(ctx context.Context, in *GetByTokenReq, opts ...grpc.CallOption) (*GetByTokenResp, error) {
	out := new(GetByTokenResp)
	err := c.cc.Invoke(ctx, "/rpc.Accounts/GetByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	GetByToken(context.Context, *GetByTokenReq) (*GetByTokenResp, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_GetByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Accounts/GetByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetByToken(ctx, req.(*GetByTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByToken",
			Handler:    _Accounts_GetByToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/app.proto",
}

func init() { proto.RegisterFile("proto/app.proto", fileDescriptor_app_0233802bd5984bdb) }

var fileDescriptor_app_0233802bd5984bdb = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x6d, 0xc8, 0xa6, 0x49, 0x66, 0x93, 0x05, 0x0d, 0x1c, 0xa2, 0xc0, 0xa1, 0x32, 0x05, 0xf6,
	0x94, 0xa2, 0xe5, 0x00, 0x57, 0x58, 0xd0, 0x0a, 0x71, 0x73, 0xb9, 0xaf, 0x4c, 0x18, 0x81, 0xb4,
	0xa4, 0x76, 0x6d, 0x2f, 0x6a, 0x2e, 0xfc, 0x76, 0xe4, 0x49, 0xd2, 0x14, 0xc1, 0x81, 0xdb, 0xcc,
	0x9b, 0xe7, 0x37, 0x1f, 0xcf, 0x70, 0xdf, 0x58, 0xed, 0xf5, 0x85, 0x32, 0xa6, 0xe1, 0x08, 0x63,
	0x6b, 0x5a, 0x71, 0x09, 0xd9, 0xa5, 0xd7, 0x96, 0x24, 0x5d, 0xe3, 0x03, 0x88, 0x0f, 0xd4, 0x57,
	0xd1, 0x59, 0xb4, 0xce, 0x65, 0x08, 0x03, 0xf2, 0x53, 0xfd, 0xa8, 0xee, 0x9d, 0x45, 0xeb, 0x42,
	0x86, 0x10, 0x9f, 0x42, 0xa9, 0xda, 0x56, 0x1f, 0xaf, 0xfc, 0xde, 0xeb, 0x03, 0x5d, 0x55, 0x31,
	0xb3, 0x8b, 0x11, 0xfc, 0x1c, 0x30, 0xb1, 0x84, 0x7c, 0x14, 0x75, 0x46, 0xd4, 0x70, 0xba, 0x23,
	0xff, 0x4f, 0x7d, 0xf1, 0x18, 0x52, 0xae, 0x39, 0x33, 0xb5, 0x8a, 0x6e, 0x5b, 0x89, 0x1c, 0xd2,
	0xf7, 0xc7, 0xce, 0x48, 0xba, 0x16, 0x0d, 0x64, 0x21, 0xfc, 0xe8, 0xa9, 0xfb, 0x9f, 0x29, 0xc5,
	0x33, 0x28, 0x77, 0xe4, 0xdf, 0xf5, 0x3c, 0x4e, 0x68, 0xfd, 0x08, 0x92, 0x61, 0xdc, 0xe1, 0xd9,
	0x90, 0x88, 0x37, 0xb0, 0xba, 0x4b, 0x73, 0x06, 0x9f, 0x43, 0x3a, 0x6e, 0xc2, 0xcc, 0xe5, 0xa6,
	0x68, 0xac, 0x69, 0x9b, 0xb7, 0x03, 0x26, 0xa7, 0xa2, 0xb8, 0x80, 0x74, 0xc4, 0xf0, 0x1c, 0x56,
	0x9d, 0xba, 0xd9, 0xb7, 0xaa, 0xfd, 0x4e, 0xfb, 0x03, 0xf5, 0x8e, 0x5f, 0xc6, 0xb2, 0xe8, 0xd4,
	0xcd, 0x36, 0x80, 0x9f, 0xa8, 0x77, 0xa2, 0x87, 0xe4, 0x83, 0xb5, 0xda, 0x22, 0xc2, 0xa2, 0xd5,
	0x5f, 0x69, 0x24, 0x71, 0x8c, 0x15, 0xa4, 0x1d, 0x39, 0xa7, 0xbe, 0x11, 0x2f, 0x91, 0xcb, 0x29,
	0xc5, 0x27, 0x90, 0x7b, 0xea, 0x8c, 0xb6, 0xca, 0xf6, 0x7c, 0xea, 0x4c, 0xce, 0x00, 0x9e, 0x43,
	0x79, 0x74, 0x64, 0x59, 0x78, 0x1b, 0x44, 0x17, 0x2c, 0xfa, 0x27, 0xb8, 0xf9, 0x05, 0x09, 0xcf,
	0x81, 0x6b, 0x48, 0xd8, 0x16, 0x2c, 0x79, 0xa9, 0xc9, 0xf7, 0x7a, 0x75, 0x37, 0x75, 0x46, 0x9c,
	0xa0, 0x80, 0x78, 0x47, 0x1e, 0x97, 0x5c, 0x18, 0xdc, 0xab, 0x8b, 0x39, 0x61, 0xce, 0x0b, 0x58,
	0x04, 0x4f, 0x70, 0xc0, 0x47, 0xa7, 0xea, 0xf2, 0x36, 0x0b, 0x66, 0x89, 0x93, 0x97, 0xd1, 0x66,
	0x0b, 0xd9, 0x78, 0x2b, 0x87, 0xaf, 0x01, 0xe6, 0x8b, 0x23, 0x4e, 0x92, 0xb3, 0x53, 0xf5, 0xc3,
	0xbf, 0xb0, 0xd0, 0xed, 0xcb, 0x29, 0xff, 0xd9, 0x57, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x38,
	0x83, 0x86, 0x6b, 0xc6, 0x02, 0x00, 0x00,
}
